# Generated by Django 5.2.14 on 2026-05-21 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('portal', models.CharField(choices=[('public', 'Portail public'), ('admin', 'Portail admin'), ('api', 'API')], db_index=True, default='public', max_length=10)),
                ('host', models.CharField(blank=True, db_index=True, max_length=120)),
                ('path', models.CharField(db_index=True, max_length=400)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visite de page',
                'verbose_name_plural': 'Visites de page',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_p_created_9ccd2b_idx'), models.Index(fields=['portal', 'created_at'], name='analytics_p_portal_2b8c76_idx'), models.Index(fields=['country_code', 'created_at'], name='analytics_p_country_01f325_idx')],
            },
        ),
    ]
