# Generated by Django 5.2.14 on 2026-06-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0002_data_retention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataretentionpolicy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Politique de rétention des données', 'verbose_name_plural': 'Politiques de rétention'},
        ),
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Abonnement push', 'verbose_name_plural': 'Abonnements push'},
        ),
        migrations.RenameIndex(
            model_name='dataaccesslog',
            new_name='companion_d_travele_8ddb6b_idx',
            old_name='companion_d_travele_1c3f8a_idx',
        ),
        migrations.RenameIndex(
            model_name='dataaccesslog',
            new_name='companion_d_resourc_4ffacf_idx',
            old_name='companion_d_resourc_2d9b6e_idx',
        ),
        migrations.RenameIndex(
            model_name='privacyconsent',
            new_name='companion_p_travele_3e36b1_idx',
            old_name='companion_p_travele_b6f0e2_idx',
        ),
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='companion_p_travele_4f6786_idx',
            old_name='companion_p_travele_a26b87_idx',
        ),
        migrations.RenameIndex(
            model_name='travelerlocationping',
            new_name='companion_t_travele_a7e96f_idx',
            old_name='companion_t_travele_8c91f4_idx',
        ),
        migrations.RenameIndex(
            model_name='travelerlocationping',
            new_name='companion_t_event_t_d4faa3_idx',
            old_name='companion_t_event_t_5dbe2c_idx',
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataaccesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datapurgelog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapurgelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privacyconsent',
            name='consent_text_excerpt',
            field=models.TextField(blank=True, help_text="Snapshot du texte exact présenté à l'utilisateur.", verbose_name='Extrait du texte consenti'),
        ),
        migrations.AlterField(
            model_name='privacyconsent',
            name='consent_version',
            field=models.CharField(default='v1', help_text="Ex : 'v1.0-2026-05'.", max_length=20, verbose_name='Version politique'),
        ),
        migrations.AlterField(
            model_name='privacyconsent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='privacyconsent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='travelerlocationping',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelerlocationping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
