# Generated by Django 5.2.14 on 2026-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltraveler',
            name='passport_document',
            field=models.TextField(blank=True, help_text='PDF, JPG ou PNG — 8 Mo maximum.', max_length=100, null=True, verbose_name='Copie du passeport / document de voyage'),
        ),
        migrations.AddField(
            model_name='historicaltraveler',
            name='passport_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='passport_document',
            field=models.FileField(blank=True, help_text='PDF, JPG ou PNG — 8 Mo maximum.', null=True, upload_to='passports/%Y/%m/', verbose_name='Copie du passeport / document de voyage'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='passport_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
