# Generated by Django 5.2.14 on 2026-05-20 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diseases', '0001_initial'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], db_index=True, default='info', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('ack', 'Reconnue'), ('investigating', 'En investigation'), ('resolved', 'Résolue'), ('dismissed', 'Rejetée')], db_index=True, default='open', max_length=20)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ack_alerts', to=settings.AUTH_USER_MODEL)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='diseases.disease')),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='geo.entrypoint')),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='geo.healthzone')),
            ],
            options={
                'verbose_name': 'Alerte sanitaire',
                'verbose_name_plural': 'Alertes sanitaires',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['severity', 'status'], name='surveillanc_severit_b22294_idx'), models.Index(fields=['disease', 'created_at'], name='surveillanc_disease_2edeba_idx')],
            },
        ),
    ]
