[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = -ra --reuse-db --strict-markers
testpaths = tests apps
markers =
    integration: tests d'intégration (DB, Redis)
    slow: tests lents
