# Generated by Django 5.2.14 on 2026-05-28 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_multicanal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_travele_1ecc92_idx',
            old_name='notif_traveler_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_provide_61ad13_idx',
            old_name='notif_provider_msgid_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationauditlog',
            new_name='notificatio_notific_c54352_idx',
            old_name='notif_audit_notif_created_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro normalisé au format E.164 (+225XXXXXXXXXX).', max_length=24),
        ),
        migrations.AlterField(
            model_name='notification',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de message côté fournisseur (utilisé pour les webhooks de statut).', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.CharField(help_text='Adresse brute saisie (téléphone, email, FCM token).', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Agent qui a envoyé le message (null pour envois automatiques).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfig',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, help_text='Code pays ISO (ex: CI) pour routage géographique. Vide = international.', max_length=4),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfig',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Réglages spécifiques (timeout, quotas, etc.).'),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfig',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, help_text='Ordre de préférence si plusieurs providers couvrent le même canal. Plus bas = prioritaire.'),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfig',
            name='sender_name',
            field=models.CharField(blank=True, help_text="Nom d'expéditeur affiché (Sender ID Orange CI, ou numéro Twilio).", max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='variables_schema',
            field=models.JSONField(blank=True, default=dict, help_text="Schema des variables disponibles dans le template. Ex: {'first_name': 'str', 'checkin_link': 'url'}"),
        ),
    ]
