# Generated by Django 5.2.14 on 2026-06-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_email_basemodel_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='notificatio_status_d84ea4_idx',
            old_name='notif_emaillog_status_created',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='notificatio_email_t_e9837a_idx',
            old_name='notif_emaillog_type_created',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='notificatio_recipie_02c093_idx',
            old_name='notif_emaillog_recipient_idx',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='senderprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
    ]
