# Generated by Django 5.2.14 on 2026-05-20 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
        ('geo', '0001_initial'),
        ('travelers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pass_number', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('investigation_ref', models.CharField(blank=True, db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('revoked', 'Révoqué'), ('blacklisted', 'Liste noire')], db_index=True, default='active', max_length=20)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('signature_b64', models.TextField(blank=True)),
                ('signing_kid', models.CharField(blank=True, help_text='Identifiant de la clé utilisée.', max_length=32)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=200)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='passes/qr/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='passes/pdf/')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to='diseases.disease')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_passes', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_passes', to='travelers.traveler')),
            ],
            options={
                'verbose_name': 'Pass sanitaire',
                'verbose_name_plural': 'Pass sanitaires',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassBlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pass_number', models.CharField(db_index=True, max_length=24, unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pass en liste noire',
                'verbose_name_plural': 'Liste noire',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pass_number', models.CharField(db_index=True, max_length=24)),
                ('verified_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_valid', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_verifications', to='geo.entrypoint')),
                ('pass_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='health_pass.healthpass')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vérification de pass',
                'verbose_name_plural': 'Vérifications de pass',
                'ordering': ['-verified_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='healthpass',
            index=models.Index(fields=['status', 'expires_at'], name='health_pass_status_8668de_idx'),
        ),
    ]
