# Generated by Django 5.2.14 on 2026-06-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caseclassification',
            new_name='medical_cas_followu_5d50d0_idx',
            old_name='medical_cc_case_current_idx',
        ),
        migrations.RenameIndex(
            model_name='caseclassification',
            new_name='medical_cas_classif_7a7343_idx',
            old_name='medical_cc_class_idx',
        ),
        migrations.RenameIndex(
            model_name='followupaction',
            new_name='medical_fol_followu_5d2351_idx',
            old_name='medical_fa_case_perf_idx',
        ),
        migrations.RenameIndex(
            model_name='followupaction',
            new_name='medical_fol_action__903a3f_idx',
            old_name='medical_fa_type_idx',
        ),
        migrations.RenameIndex(
            model_name='labanalysis',
            new_name='medical_lab_sample__477a7e_idx',
            old_name='medical_lab_sample_idx',
        ),
        migrations.RenameIndex(
            model_name='labanalysis',
            new_name='medical_lab_status_09b5fe_idx',
            old_name='medical_lab_status_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalsample',
            new_name='medical_med_followu_0d72e7_idx',
            old_name='medical_sample_case_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalsample',
            new_name='medical_med_transpo_7c385f_idx',
            old_name='medical_sample_status_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalsymptomreport',
            new_name='medical_med_followu_93c592_idx',
            old_name='medical_msr_case_onset_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalsymptomreport',
            new_name='medical_med_is_crit_5c55f2_idx',
            old_name='medical_msr_critical_idx',
        ),
    ]
