# Generated by Django 5.2.14 on 2026-05-20 23:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
        ('travelers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('investigation_ref', models.CharField(blank=True, db_index=True, max_length=24)),
                ('started_on', models.DateField(db_index=True)),
                ('expected_end_on', models.DateField(db_index=True)),
                ('actual_end_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('broken', 'Rompue'), ('extended', 'Prolongée'), ('cancelled', 'Annulée')], db_index=True, default='active', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantines', to='diseases.disease')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_quarantines', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantines', to='travelers.traveler')),
            ],
            options={
                'verbose_name': 'Quarantaine',
                'verbose_name_plural': 'Quarantaines',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUpVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visit_datetime', models.DateTimeField(db_index=True)),
                ('found_person', models.BooleanField(default=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('observations', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='quarantine/visits/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits_done', to=settings.AUTH_USER_MODEL)),
                ('quarantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='quarantine.quarantinerecord')),
            ],
            options={
                'verbose_name': 'Visite de suivi',
                'verbose_name_plural': 'Visites de suivi',
                'ordering': ['-visit_datetime'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day_index', models.PositiveSmallIntegerField(help_text='Jour J0..J21 du suivi.')),
                ('check_date', models.DateField(db_index=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('has_symptoms', models.BooleanField(default=False)),
                ('symptoms_details', models.JSONField(blank=True, default=dict)),
                ('is_self_reported', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('alert_raised', models.BooleanField(default=False)),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_checks', to=settings.AUTH_USER_MODEL)),
                ('quarantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to='quarantine.quarantinerecord')),
            ],
            options={
                'verbose_name': 'Suivi quotidien',
                'verbose_name_plural': 'Suivis quotidiens',
                'ordering': ['quarantine', 'day_index'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='quarantinerecord',
            index=models.Index(fields=['status', 'expected_end_on'], name='quarantine__status_d66b1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycheck',
            constraint=models.UniqueConstraint(fields=('quarantine', 'day_index'), name='uniq_check_per_day'),
        ),
    ]
