# Generated by Django 5.2.14 on 2026-06-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarantine', '0002_phase9a_extend_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quarantinerecord',
            new_name='quarantine__assigne_2fe39c_idx',
            old_name='quarantine_agent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='quarantinerecord',
            new_name='quarantine__current_beb28f_idx',
            old_name='quarantine_classif_status_idx',
        ),
    ]
