# Generated by Django 5.2.14 on 2026-05-20 23:36

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='code')),
                ('short_name', models.CharField(blank=True, max_length=40, verbose_name='nom court')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icd11_code', models.CharField(blank=True, max_length=40, verbose_name='code CIM-11')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modérée'), ('high', 'Élevée'), ('critical', 'Critique')], default='moderate', max_length=20, verbose_name='gravité')),
                ('color', models.CharField(default='#dc2626', max_length=9, verbose_name='couleur (hex)')),
                ('incubation_min_days', models.PositiveSmallIntegerField(default=1, verbose_name='incubation min (jours)')),
                ('incubation_max_days', models.PositiveSmallIntegerField(default=14, verbose_name='incubation max (jours)')),
                ('surveillance_days', models.PositiveSmallIntegerField(default=21, verbose_name='durée surveillance (jours)')),
                ('quarantine_days', models.PositiveSmallIntegerField(default=21, verbose_name='durée quarantaine (jours)')),
                ('transmission_modes', models.JSONField(blank=True, default=list, verbose_name='modes de transmission')),
                ('risk_countries', models.JSONField(blank=True, default=list, help_text='Liste de codes pays ISO-2 considérés à risque.', verbose_name='pays à risque (ISO-2)')),
                ('case_definition', models.TextField(blank=True, verbose_name='définition de cas')),
                ('protocols', models.JSONField(blank=True, default=dict, verbose_name='protocoles')),
                ('notification_rules', models.JSONField(blank=True, default=dict, verbose_name='règles de notification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('requires_quarantine', models.BooleanField(default=True, verbose_name='requiert quarantaine')),
                ('requires_pass', models.BooleanField(default=True, verbose_name='requiert un pass sanitaire')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDisease',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='nom')),
                ('code', models.SlugField(max_length=40, verbose_name='code')),
                ('short_name', models.CharField(blank=True, max_length=40, verbose_name='nom court')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icd11_code', models.CharField(blank=True, max_length=40, verbose_name='code CIM-11')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modérée'), ('high', 'Élevée'), ('critical', 'Critique')], default='moderate', max_length=20, verbose_name='gravité')),
                ('color', models.CharField(default='#dc2626', max_length=9, verbose_name='couleur (hex)')),
                ('incubation_min_days', models.PositiveSmallIntegerField(default=1, verbose_name='incubation min (jours)')),
                ('incubation_max_days', models.PositiveSmallIntegerField(default=14, verbose_name='incubation max (jours)')),
                ('surveillance_days', models.PositiveSmallIntegerField(default=21, verbose_name='durée surveillance (jours)')),
                ('quarantine_days', models.PositiveSmallIntegerField(default=21, verbose_name='durée quarantaine (jours)')),
                ('transmission_modes', models.JSONField(blank=True, default=list, verbose_name='modes de transmission')),
                ('risk_countries', models.JSONField(blank=True, default=list, help_text='Liste de codes pays ISO-2 considérés à risque.', verbose_name='pays à risque (ISO-2)')),
                ('case_definition', models.TextField(blank=True, verbose_name='définition de cas')),
                ('protocols', models.JSONField(blank=True, default=dict, verbose_name='protocoles')),
                ('notification_rules', models.JSONField(blank=True, default=dict, verbose_name='règles de notification')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='actif')),
                ('requires_quarantine', models.BooleanField(default=True, verbose_name='requiert quarantaine')),
                ('requires_pass', models.BooleanField(default=True, verbose_name='requiert un pass sanitaire')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Maladie',
                'verbose_name_plural': 'historical Maladies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='diseases.disease')),
            ],
            options={
                'verbose_name': 'Facteur de risque',
                'verbose_name_plural': 'Facteurs de risque',
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('disease', 'code'), name='uniq_risk_factor_per_disease')],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=160)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Poids du symptôme dans le calcul du score de risque.')),
                ('is_red_flag', models.BooleanField(default=False, help_text='Symptôme alarmant (saignement, etc.)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='diseases.disease')),
            ],
            options={
                'verbose_name': 'Symptôme',
                'verbose_name_plural': 'Symptômes',
                'ordering': ['disease', 'order', 'label'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('disease', 'code'), name='uniq_symptom_per_disease')],
            },
        ),
    ]
