# Generated by Django 5.2.14 on 2026-06-21 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mfa_email_and_security'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotpcode',
            new_name='accounts_em_user_id_c38ace_idx',
            old_name='acct_otp_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotpcode',
            new_name='accounts_em_expires_ee4c9e_idx',
            old_name='acct_otp_expires_idx',
        ),
        migrations.AlterField(
            model_name='emailotpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='emailotpcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='emailotpcode',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Verrouillage temporaire automatique.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Force le changement de mot de passe à la prochaine connexion.'),
        ),
    ]
