# Generated by Django 5.2.14 on 2026-05-20 23:36

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('geo', '0001_initial'),
        ('travelers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbolaInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('case_number', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_review', 'En revue'), ('cleared', 'Autorisé'), ('surveillance', 'Sous surveillance'), ('quarantine', 'Quarantaine'), ('suspect', 'Cas suspect'), ('probable', 'Cas probable'), ('confirmed', 'Cas confirmé'), ('recovered', 'Rétabli'), ('deceased', 'Décédé'), ('closed', 'Clôturé')], db_index=True, default='new', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé'), ('critical', 'Critique')], db_index=True, default='low', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('surveillance_start', models.DateField(blank=True, null=True)),
                ('surveillance_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('entry_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebola_investigations', to='geo.entrypoint')),
                ('investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebola_investigations', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebola_investigation', to='forms.formsubmission')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebola_investigations', to='travelers.traveler')),
            ],
            options={
                'verbose_name': 'Enquête Ebola',
                'verbose_name_plural': 'Enquêtes Ebola',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbolaExposureAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visited_ebola_zone', models.BooleanField(default=False, verbose_name="Q1. Séjourné ou transité par une zone touchée par l'épidémie d'Ebola")),
                ('visited_ebola_zone_details', models.CharField(blank=True, max_length=300, verbose_name='Si oui, précisez la ville/région et le pays')),
                ('contact_with_case', models.BooleanField(default=False, verbose_name="Q2. Contact avec une personne malade ou suspectée d'Ebola")),
                ('attended_funeral_or_touched_corpse', models.BooleanField(default=False, verbose_name='Q3. Funérailles ou contact avec une dépouille humaine')),
                ('visited_ebola_healthcare_facility', models.BooleanField(default=False, verbose_name='Q4. Fréquenté un établissement de soins traitant des patients Ebola')),
                ('raw_exposure_score', models.PositiveSmallIntegerField(default=0)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exposure', to='ebola.ebolainvestigation')),
            ],
            options={
                'verbose_name': "Évaluation d'exposition (Section 5)",
                'verbose_name_plural': "Évaluations d'exposition (Section 5)",
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbolaDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('declared_at', models.DateTimeField()),
                ('declarant_full_name', models.CharField(max_length=240)),
                ('signed_place', models.CharField(blank=True, max_length=120, verbose_name='Fait à')),
                ('truthful_declaration', models.BooleanField(default=False, verbose_name="Certification sur l'honneur de l'exactitude des renseignements")),
                ('consent_data_processing', models.BooleanField(default=False)),
                ('consent_health_followup', models.BooleanField(default=False)),
                ('consent_quarantine_if_needed', models.BooleanField(default=False)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='ebola/signatures/')),
                ('signature_hash', models.CharField(blank=True, max_length=128)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='ebola.ebolainvestigation')),
            ],
            options={
                'verbose_name': 'Déclaration Ebola (Section 7)',
                'verbose_name_plural': 'Déclarations Ebola (Section 7)',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbolaSymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reported_at', models.DateTimeField()),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fever', models.BooleanField(default=False, verbose_name='S1. Fièvre (≥38°C) / sensation de forte chaleur')),
                ('intense_fatigue', models.BooleanField(default=False, verbose_name='S2. Fatigue intense / faiblesse généralisée')),
                ('muscle_joint_pain', models.BooleanField(default=False, verbose_name='S3. Douleurs musculaires, articulaires, courbatures')),
                ('severe_headache', models.BooleanField(default=False, verbose_name='S4. Maux de tête intenses (Céphalées)')),
                ('sore_throat_or_abdominal', models.BooleanField(default=False, verbose_name='S5. Maux de gorge ou douleurs abdominales (estomac)')),
                ('diarrhea_nausea_vomiting', models.BooleanField(default=False, verbose_name='S6. Diarrhée, nausées ou vomissements fréquents')),
                ('unexplained_bleeding', models.BooleanField(default=False, verbose_name='S7. Saignements inexpliqués (nez, gencives, peau, urines, selles)')),
                ('other_symptoms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to='ebola.ebolainvestigation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebola_symptom_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de symptômes Ebola (Section 6)',
                'verbose_name_plural': 'Rapports de symptômes Ebola (Section 6)',
                'ordering': ['-reported_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalEbolaInvestigation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('case_number', models.CharField(db_index=True, editable=False, max_length=24)),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_review', 'En revue'), ('cleared', 'Autorisé'), ('surveillance', 'Sous surveillance'), ('quarantine', 'Quarantaine'), ('suspect', 'Cas suspect'), ('probable', 'Cas probable'), ('confirmed', 'Cas confirmé'), ('recovered', 'Rétabli'), ('deceased', 'Décédé'), ('closed', 'Clôturé')], db_index=True, default='new', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé'), ('critical', 'Critique')], db_index=True, default='low', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('surveillance_start', models.DateField(blank=True, null=True)),
                ('surveillance_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('entry_point', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.entrypoint')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investigator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forms.formsubmission')),
                ('traveler', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='travelers.traveler')),
            ],
            options={
                'verbose_name': 'historical Enquête Ebola',
                'verbose_name_plural': 'historical Enquêtes Ebola',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='ebolainvestigation',
            index=models.Index(fields=['status', 'risk_level'], name='ebola_ebola_status_608ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='ebolainvestigation',
            index=models.Index(fields=['entry_point', 'created_at'], name='ebola_ebola_entry_p_4bf259_idx'),
        ),
    ]
