# Generated by Django 5.2.14 on 2026-06-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assistancerequest',
            new_name='mobile_api__status_b25c74_idx',
            old_name='ass_req_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assistancerequest',
            new_name='mobile_api__user_id_6625e1_idx',
            old_name='ass_req_user_idx',
        ),
        migrations.RenameIndex(
            model_name='locationshare',
            new_name='mobile_api__user_id_71a3d8_idx',
            old_name='loc_share_user_idx',
        ),
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='mobile_api__user_id_8a714f_idx',
            old_name='mobi_dev_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='mobile_api__fcm_tok_b6ba8c_idx',
            old_name='mobi_dev_token_idx',
        ),
        migrations.RenameIndex(
            model_name='vaccination',
            new_name='mobile_api__user_id_cf43ea_idx',
            old_name='vacc_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='vaccination',
            new_name='mobile_api__disease_79ac13_idx',
            old_name='vacc_disease_idx',
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='assistancerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='locationshare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='locationshare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='device_id',
            field=models.CharField(blank=True, help_text='ANDROID_ID ou identifierForVendor — non identifiant utilisateur', max_length=200, verbose_name='identifiant appareil'),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='disease_code',
            field=models.CharField(db_index=True, help_text='ex: YELLOW_FEVER, COVID19, EBOLA, MPOX, HEPATITIS_B', max_length=40, verbose_name='code maladie'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
    ]
