# Generated by Django 5.2.14 on 2026-05-20 23:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='code ISO-2')),
                ('code3', models.CharField(blank=True, db_index=True, max_length=3, verbose_name='code ISO-3')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='nom')),
                ('name_local', models.CharField(blank=True, max_length=120, verbose_name='nom local')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='région')),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé'), ('red', 'Zone rouge')], default='low', max_length=20)),
                ('risk_for_diseases', models.JSONField(blank=True, default=list, help_text='Liste de codes maladie pour lesquelles ce pays est à risque.')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('level', models.CharField(choices=[('country', 'Pays'), ('region', 'Région'), ('district', 'District'), ('commune', 'Commune'), ('custom', 'Zone personnalisée')], default='district', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modéré'), ('high', 'Élevé'), ('red', 'Zone rouge')], default='low', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geo.healthzone')),
            ],
            options={
                'verbose_name': 'Zone sanitaire',
                'verbose_name_plural': 'Zones sanitaires',
                'ordering': ['level', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('type', models.CharField(choices=[('airport', 'Aéroport'), ('seaport', 'Port maritime'), ('land', 'Frontière terrestre'), ('river', 'Point fluvial'), ('other', 'Autre')], db_index=True, max_length=20)),
                ('iata_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('icao_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_points', to='geo.country')),
            ],
            options={
                'verbose_name': "Point d'entrée",
                'verbose_name_plural': "Points d'entrée",
                'ordering': ['name'],
                'abstract': False,
                'indexes': [models.Index(fields=['type', 'is_active'], name='geo_entrypo_type_5bb264_idx')],
            },
        ),
    ]
